#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

/**
 * 板级硬件 IO（引脚 / 总线脚位）。
 * 产品功能开关见 board_features.h；模块参数见各 *_config.h。
 * 联调剖面说明见 FEATURE_FLAGS.md。
 */

/* -------- 自由引出脚 GPIO38/48：成对模式 --------
 * 必须用 #define 数值（不能仅用 enum）：#if 里未定义的标识符一律当 0，
 * 若用 enum 常量比较会出现 NONE==CAN 恒真，MODE_STR 误报 can。
 */
#define DEEP_DOG_EXT_PIN_NONE  0
#define DEEP_DOG_EXT_PIN_CAN   1
#define DEEP_DOG_EXT_PIN_UART  2
#define DEEP_DOG_EXT_PIN_RS485 3
#define DEEP_DOG_EXT_PIN_PWM   4
#define DEEP_DOG_EXT_PIN_IO    5
#define DEEP_DOG_EXT_PIN_AD    6
#define DEEP_DOG_EXT_PIN_LED   7

typedef int deep_dog_ext_pin_mode_t;

/** 联调默认 CAN（单电机）；云台改回 _PWM，灯带 _LED，前端壳 _NONE */
#ifndef DEEP_DOG_EXT_PIN_MODE
#define DEEP_DOG_EXT_PIN_MODE DEEP_DOG_EXT_PIN_LED
#endif

#define DEEP_DOG_EXT_PIN_A_GPIO GPIO_NUM_38
#define DEEP_DOG_EXT_PIN_B_GPIO GPIO_NUM_48

/* 由模式推导硬件可用性（不直接打开产品链） */
#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_CAN
#define DEEP_DOG_CAN_AVAILABLE 1
#else
#define DEEP_DOG_CAN_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_UART
#define DEEP_DOG_UART_AVAILABLE 1
#else
#define DEEP_DOG_UART_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_RS485
#define DEEP_DOG_RS485_AVAILABLE 1
#else
#define DEEP_DOG_RS485_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_PWM
#define DEEP_DOG_PWM_AVAILABLE 1
#else
#define DEEP_DOG_PWM_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_IO
#define DEEP_DOG_IO_AVAILABLE 1
#else
#define DEEP_DOG_IO_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_AD
#define DEEP_DOG_AD_AVAILABLE 1
#else
#define DEEP_DOG_AD_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_LED
#define DEEP_DOG_LED_AVAILABLE 1
#else
#define DEEP_DOG_LED_AVAILABLE 0
#endif

#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_CAN
#define DEEP_DOG_EXT_PIN_MODE_STR "can"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_UART
#define DEEP_DOG_EXT_PIN_MODE_STR "uart"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_RS485
#define DEEP_DOG_EXT_PIN_MODE_STR "rs485"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_PWM
#define DEEP_DOG_EXT_PIN_MODE_STR "pwm"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_IO
#define DEEP_DOG_EXT_PIN_MODE_STR "io"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_AD
#define DEEP_DOG_EXT_PIN_MODE_STR "ad"
#elif DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_LED
#define DEEP_DOG_EXT_PIN_MODE_STR "led"
#else
#define DEEP_DOG_EXT_PIN_MODE_STR "none"
#endif

#include "board_features.h"

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_45
#define AUDIO_I2S_GPIO_WS GPIO_NUM_41
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_40
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_42

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_4
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_5
#ifndef I2C_MASTER_FREQ_HZ
#define I2C_MASTER_FREQ_HZ       (400 * 1000)
#endif
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_DC_GPIO     GPIO_NUM_43
#define DISPLAY_CS_GPIO     GPIO_NUM_44
#define DISPLAY_CLK_GPIO    GPIO_NUM_21
#define DISPLAY_MOSI_GPIO   GPIO_NUM_47
#define DISPLAY_RST_GPIO    GPIO_NUM_NC

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

/* Camera：与 ESP-SparkBot 一致；SCCB 与 ES8311 共用 I2C0 */
#define SPARKBOT_CAMERA_XCLK      (GPIO_NUM_15)
#define SPARKBOT_CAMERA_PCLK      (GPIO_NUM_13)
#define SPARKBOT_CAMERA_VSYNC     (GPIO_NUM_6)
#define SPARKBOT_CAMERA_HSYNC     (GPIO_NUM_7)
#define SPARKBOT_CAMERA_D0        (GPIO_NUM_11)
#define SPARKBOT_CAMERA_D1        (GPIO_NUM_9)
#define SPARKBOT_CAMERA_D2        (GPIO_NUM_8)
#define SPARKBOT_CAMERA_D3        (GPIO_NUM_10)
#define SPARKBOT_CAMERA_D4        (GPIO_NUM_12)
#define SPARKBOT_CAMERA_D5        (GPIO_NUM_18)
#define SPARKBOT_CAMERA_D6        (GPIO_NUM_17)
#define SPARKBOT_CAMERA_D7        (GPIO_NUM_16)

#define SPARKBOT_CAMERA_PWDN      (GPIO_NUM_NC)
#define SPARKBOT_CAMERA_RESET     (GPIO_NUM_NC)
#define SPARKBOT_CAMERA_XCLK_FREQ (16000000)
#ifndef DEEP_DOG_CAMERA_INIT_DELAY_MS
#define DEEP_DOG_CAMERA_INIT_DELAY_MS 200
#endif
#ifndef DEEP_DOG_CAMERA_INIT_RETRIES
#define DEEP_DOG_CAMERA_INIT_RETRIES 2
#endif
#ifndef DEEP_DOG_CAMERA_INIT_RETRY_GAP_MS
#define DEEP_DOG_CAMERA_INIT_RETRY_GAP_MS 300
#endif
/** 摄像头方向（EspVideo SetHMirror / SetVFlip）；SparkBot 默认均为 0；上下反了可试 V_FLIP=1 或 H+V 均为 1 */
#ifndef DEEP_DOG_CAMERA_H_MIRROR
#define DEEP_DOG_CAMERA_H_MIRROR 0
#endif
#ifndef DEEP_DOG_CAMERA_V_FLIP
#define DEEP_DOG_CAMERA_V_FLIP 1
#endif
#define SPARKBOT_LEDC_TIMER       (LEDC_TIMER_0)
#define SPARKBOT_LEDC_CHANNEL     (LEDC_CHANNEL_0)

#define SPARKBOT_CAMERA_SIOD      (GPIO_NUM_NC)
#define SPARKBOT_CAMERA_SIOC      (GPIO_NUM_NC)

/* 触摸按键 */
#define TOUCH_BUTTON1_GPIO       (GPIO_NUM_1)
#define TOUCH_BUTTON2_GPIO       (GPIO_NUM_2)
#define TOUCH_BUTTON3_GPIO       (GPIO_NUM_3)

/* 灯带：mode=led 时默认 DIN=gpio_a(38)、count=24；其它 mode 默认 NC/0（可覆盖） */
#if DEEP_DOG_EXT_PIN_MODE == DEEP_DOG_EXT_PIN_LED
#ifndef DEEP_DOG_LED_STRIP_GPIO
#define DEEP_DOG_LED_STRIP_GPIO  DEEP_DOG_EXT_PIN_A_GPIO
#endif
#ifndef DEEP_DOG_LED_STRIP_COUNT
#define DEEP_DOG_LED_STRIP_COUNT 24
#endif
#else
#ifndef DEEP_DOG_LED_STRIP_GPIO
#define DEEP_DOG_LED_STRIP_GPIO  GPIO_NUM_NC
#endif
#ifndef DEEP_DOG_LED_STRIP_COUNT
#define DEEP_DOG_LED_STRIP_COUNT 0
#endif
#endif

#endif // _BOARD_CONFIG_H_
