#ifndef _DEEP_DOG_RS485_CONFIG_H_
#define _DEEP_DOG_RS485_CONFIG_H_
#include "config.h"
#if DEEP_DOG_RS485_AVAILABLE
#ifndef DEEP_DOG_RS485_TX_GPIO
#define DEEP_DOG_RS485_TX_GPIO DEEP_DOG_EXT_PIN_A_GPIO
#endif
#ifndef DEEP_DOG_RS485_RX_GPIO
#define DEEP_DOG_RS485_RX_GPIO DEEP_DOG_EXT_PIN_B_GPIO
#endif
#endif
#endif
